from fantasy_baseball_manager.domain.adp import ADP
from fantasy_baseball_manager.domain.adp_accuracy import (
    ADPAccuracyPlayer,
    ADPAccuracyReport,
    ADPAccuracyResult,
    SystemAccuracyResult,
)
from fantasy_baseball_manager.domain.adp_arbitrage import (
    ArbitrageReport,
    FallingPlayer,
    ReachPick,
)
from fantasy_baseball_manager.domain.adp_movers import ADPMover, ADPMoversReport
from fantasy_baseball_manager.domain.adp_report import ValueOverADP, ValueOverADPReport
from fantasy_baseball_manager.domain.batting_stats import BattingStats
from fantasy_baseball_manager.domain.breakout_bust import (
    BreakoutPrediction,
    ClassifierCalibrationBin,
    ClassifierEvaluation,
    LabelConfig,
    LabeledSeason,
    LiftResult,
    OutcomeLabel,
    ThresholdMetrics,
)
from fantasy_baseball_manager.domain.category_tracker import (
    CategoryNeed,
    PlayerRecommendation,
    RosterAnalysis,
    TeamCategoryProjection,
)
from fantasy_baseball_manager.domain.checkpoint import FeatureCheckpoint
from fantasy_baseball_manager.domain.column_profile import ColumnProfile
from fantasy_baseball_manager.domain.correlation_result import (
    CorrelationScanResult,
    MultiColumnRanking,
    PooledCorrelationResult,
    SeasonCorrelationResult,
    TargetCorrelation,
)
from fantasy_baseball_manager.domain.draft_board import (
    DraftBoard,
    DraftBoardRow,
    TierAssignment,
)
from fantasy_baseball_manager.domain.draft_plan import (
    AvailabilityWindow,
    DraftPlan,
    DraftPlanTarget,
    PickAvailability,
    PlayerAvailabilityCurve,
)
from fantasy_baseball_manager.domain.draft_recommendation import (
    Recommendation,
    RecommendationWeights,
)
from fantasy_baseball_manager.domain.draft_report import (
    CategoryStanding,
    DraftReport,
    PickGrade,
    StealOrReach,
)
from fantasy_baseball_manager.domain.draft_session import (
    DraftSessionPick,
    DraftSessionRecord,
)
from fantasy_baseball_manager.domain.error_decomposition import (
    CohortBias,
    CohortBiasReport,
    DistinguishingFeature,
    ErrorDecompositionReport,
    FeatureGap,
    FeatureGapReport,
    MissPopulationSummary,
    PlayerResidual,
    bucket_by_age,
    bucket_by_experience,
    bucket_by_handedness,
    bucket_by_position,
    compute_cohort_metrics,
    compute_distinguishing_features,
    compute_miss_summary,
    rank_residuals,
    split_direction,
    split_residuals_by_quality,
)
from fantasy_baseball_manager.domain.errors import (
    ConfigError,
    DispatchError,
    FbmError,
    IngestError,
)
from fantasy_baseball_manager.domain.evaluation import (
    ComparisonResult,
    ComparisonSummary,
    RegressionCheckResult,
    StatComparisonRecord,
    StatMetrics,
    StratifiedComparisonResult,
    SystemMetrics,
    TailAccuracy,
    check_regression,
    compute_stat_metrics,
    compute_tail_accuracy,
    summarize_comparison,
)
from fantasy_baseball_manager.domain.expected_games_lost import ExpectedGamesLost
from fantasy_baseball_manager.domain.experiment import (
    Experiment,
    ExplorationSummary,
    FeatureExplorationResult,
    TargetExplorationResult,
    TargetResult,
)
from fantasy_baseball_manager.domain.feature_candidate import (
    BinnedValue,
    BinTargetMean,
    CandidateValue,
    FeatureCandidate,
)
from fantasy_baseball_manager.domain.il_stint import ILStint
from fantasy_baseball_manager.domain.injury_discount import apply_injury_discount, discount_projections
from fantasy_baseball_manager.domain.injury_profile import InjuryProfile
from fantasy_baseball_manager.domain.injury_value_delta import InjuryValueDelta
from fantasy_baseball_manager.domain.keeper import (
    AdjustedValuation,
    KeeperCost,
    KeeperDecision,
    KeeperPlanResult,
    KeeperScenarioResult,
    LeagueKeeper,
    LeagueKeeperOverview,
    ProjectedKeeper,
    TeamKeeperProjection,
    TradeEvaluation,
    TradePlayerDetail,
    TradeTarget,
)
from fantasy_baseball_manager.domain.keeper_history import KeeperHistory, KeeperSeasonEntry
from fantasy_baseball_manager.domain.keeper_optimization import (
    KeeperConstraints,
    KeeperScenario,
    KeeperSet,
    KeeperSolution,
    KeeperTradeImpact,
    LeagueKeeperState,
    SensitivityEntry,
)
from fantasy_baseball_manager.domain.league_environment import LeagueEnvironment
from fantasy_baseball_manager.domain.league_settings import (
    CategoryConfig,
    Direction,
    EligibilityRules,
    LeagueFormat,
    LeagueSettings,
    StatType,
)
from fantasy_baseball_manager.domain.level_factor import LevelFactor
from fantasy_baseball_manager.domain.load_log import LoadLog
from fantasy_baseball_manager.domain.minor_league_batting_stats import (
    MinorLeagueBattingStats,
)
from fantasy_baseball_manager.domain.mock_draft import (
    BatchSimulationResult,
    BotStrategy,
    DraftPick,
    DraftResult,
    PlayerDraftFrequency,
    SimulationSummary,
    StrategyComparison,
)
from fantasy_baseball_manager.domain.model_protocol import (
    Ablatable,
    AblationResult,
    EligibilityProvider,
    Evaluable,
    Evaluator,
    Experimentable,
    FeatureIntrospectable,
    FineTunable,
    FittedModels,
    GamesLostEstimator,
    Model,
    ModelConfig,
    PlayerUniverseProvider,
    Predictable,
    PredictResult,
    Preparable,
    PrepareResult,
    ReplacementPadder,
    Sweepable,
    TargetComparison,
    TargetVector,
    Trainable,
    TrainingBackend,
    TrainResult,
    Tunable,
    TuneResult,
    ValidationResult,
)
from fantasy_baseball_manager.domain.model_run import ArtifactType, ModelRunRecord
from fantasy_baseball_manager.domain.opponent_model import LeagueNeeds, PositionRun, TeamNeeds, ThreatAssessment
from fantasy_baseball_manager.domain.performance_delta import PlayerStatDelta
from fantasy_baseball_manager.domain.pick_value import (
    CascadeResult,
    CascadeRoster,
    PickTrade,
    PickTradeEvaluation,
    PickValue,
    PickValueCurve,
)
from fantasy_baseball_manager.domain.pitching_stats import PitchingStats
from fantasy_baseball_manager.domain.player import Player, Team
from fantasy_baseball_manager.domain.player_bio import PlayerSummary
from fantasy_baseball_manager.domain.player_profile import PlayerProfile, compute_age
from fantasy_baseball_manager.domain.position import (
    OF_POSITIONS,
    ROSTER_ONLY_POSITIONS,
    Position,
    consolidate_outfield,
    position_from_raw,
)
from fantasy_baseball_manager.domain.position_appearance import PositionAppearance
from fantasy_baseball_manager.domain.positional_scarcity import (
    PositionScarcity,
    PositionValueCurve,
    ScarcityAdjustedPlayer,
)
from fantasy_baseball_manager.domain.positional_upgrade import (
    MarginalValue,
    OpportunityCost,
    PositionUpgrade,
    RosterSlot,
    RosterState,
)
from fantasy_baseball_manager.domain.projection import (
    PlayerProjection,
    Projection,
    PTSourceSummary,
    StatDistribution,
    SystemSummary,
)
from fantasy_baseball_manager.domain.projection_accuracy import (
    BATTING_COUNTING_STATS,
    BATTING_RATE_STATS,
    PITCHING_COUNTING_STATS,
    PITCHING_RATE_STATS,
    ProjectionComparison,
    compare_to_batting_actuals,
    compare_to_pitching_actuals,
    missing_batting_comparisons,
    missing_pitching_comparisons,
)
from fantasy_baseball_manager.domain.projection_confidence import (
    ClassifiedPlayer,
    ConfidenceReport,
    PlayerConfidence,
    StatSpread,
    VarianceClassification,
)
from fantasy_baseball_manager.domain.pt_normalization import (
    ConsensusLookup,
    build_consensus_lookup,
    normalize_projection_pt,
)
from fantasy_baseball_manager.domain.pt_resolution import resolve_playing_time
from fantasy_baseball_manager.domain.pt_scenario import PlayingTimeScenario
from fantasy_baseball_manager.domain.replacement_profile import ReplacementProfile
from fantasy_baseball_manager.domain.residual_analysis import (
    CalibrationBin,
    ResidualAnalysisReport,
    ResidualAnalysisSummary,
    StatResidualAnalysis,
    compute_calibration_bins,
    compute_heteroscedasticity,
    compute_mean_bias,
)
from fantasy_baseball_manager.domain.residual_persistence import (
    ChronicPerformer,
    ResidualPersistenceReport,
    ResidualPersistenceSummary,
    StatResidualPersistence,
    compute_residual_correlation_by_bucket,
    compute_rmse_ceiling,
    identify_chronic_performers,
)
from fantasy_baseball_manager.domain.result import Err, Ok, Result
from fantasy_baseball_manager.domain.roster import Roster, RosterEntry
from fantasy_baseball_manager.domain.roster_optimizer import (
    BudgetAllocation,
    RoundTarget,
    SnakeDraftPlan,
)
from fantasy_baseball_manager.domain.roster_stint import RosterStint
from fantasy_baseball_manager.domain.season import current_season
from fantasy_baseball_manager.domain.season_data import SeasonData
from fantasy_baseball_manager.domain.sgp import SgpDenominators, SgpSeasonDenominator
from fantasy_baseball_manager.domain.sprint_speed import SprintSpeed
from fantasy_baseball_manager.domain.statcast_pitch import StatcastPitch
from fantasy_baseball_manager.domain.talent_quality import (
    StatTalentMetrics,
    TalentQualitySummary,
    TrueTalentQualityReport,
    compute_predictive_validity,
    compute_r_squared_with_buckets,
    compute_residual_yoy_correlation,
    compute_shrinkage,
)
from fantasy_baseball_manager.domain.temporal_stability import (
    StabilityResult,
    TargetStability,
)
from fantasy_baseball_manager.domain.tier import (
    PlayerTier,
    TierSummaryEntry,
    TierSummaryReport,
)
from fantasy_baseball_manager.domain.transaction import Transaction, TransactionPlayer
from fantasy_baseball_manager.domain.valuation import (
    PlayerValuation,
    Valuation,
    ValuationAccuracy,
    ValuationComparisonResult,
    ValuationEvalResult,
    ValuationRegressionCheck,
    check_valuation_regression,
)
from fantasy_baseball_manager.domain.yahoo_draft_pick import YahooDraftPick
from fantasy_baseball_manager.domain.yahoo_league import YahooLeague, YahooTeam
from fantasy_baseball_manager.domain.yahoo_player import YahooPlayerMap
from fantasy_baseball_manager.domain.yahoo_team_stats import TeamSeasonStats

__all__ = [
    "Ablatable",
    "AblationResult",
    "ADP",
    "AdjustedValuation",
    "ArbitrageReport",
    "AvailabilityWindow",
    "BreakoutPrediction",
    "LabelConfig",
    "LabeledSeason",
    "ADPAccuracyPlayer",
    "ADPAccuracyReport",
    "ADPAccuracyResult",
    "ADPMover",
    "ADPMoversReport",
    "ArtifactType",
    "BATTING_COUNTING_STATS",
    "BATTING_RATE_STATS",
    "BattingStats",
    "BatchSimulationResult",
    "BinTargetMean",
    "BinnedValue",
    "BotStrategy",
    "CalibrationBin",
    "ClassifierCalibrationBin",
    "ClassifierEvaluation",
    "CandidateValue",
    "CohortBias",
    "CohortBiasReport",
    "CascadeResult",
    "CascadeRoster",
    "CategoryNeed",
    "RosterAnalysis",
    "CategoryConfig",
    "CategoryStanding",
    "ChronicPerformer",
    "ClassifiedPlayer",
    "ColumnProfile",
    "ComparisonResult",
    "DistinguishingFeature",
    "ErrorDecompositionReport",
    "FeatureGap",
    "FeatureGapReport",
    "ComparisonSummary",
    "CorrelationScanResult",
    "FallingPlayer",
    "FeatureCandidate",
    "FeatureCheckpoint",
    "ConfidenceReport",
    "ReplacementProfile",
    "RegressionCheckResult",
    "ConfigError",
    "ConsensusLookup",
    "Direction",
    "DispatchError",
    "apply_injury_discount",
    "discount_projections",
    "DraftPlan",
    "DraftPlanTarget",
    "DraftBoard",
    "PickAvailability",
    "PlayerAvailabilityCurve",
    "DraftBoardRow",
    "DraftPick",
    "PlayerDraftFrequency",
    "DraftReport",
    "DraftResult",
    "DraftSessionPick",
    "DraftSessionRecord",
    "EligibilityProvider",
    "EligibilityRules",
    "Err",
    "Evaluable",
    "Evaluator",
    "Experimentable",
    "ExpectedGamesLost",
    "Experiment",
    "ExplorationSummary",
    "FeatureExplorationResult",
    "FbmError",
    "FeatureIntrospectable",
    "FineTunable",
    "FittedModels",
    "GamesLostEstimator",
    "ReplacementPadder",
    "MultiColumnRanking",
    "ILStint",
    "InjuryProfile",
    "InjuryValueDelta",
    "IngestError",
    "KeeperConstraints",
    "LeagueNeeds",
    "KeeperCost",
    "KeeperDecision",
    "KeeperPlanResult",
    "KeeperScenarioResult",
    "LeagueKeeper",
    "KeeperHistory",
    "KeeperScenario",
    "KeeperSeasonEntry",
    "KeeperSet",
    "KeeperSolution",
    "KeeperTradeImpact",
    "LeagueKeeperOverview",
    "LeagueKeeperState",
    "LiftResult",
    "LeagueEnvironment",
    "LeagueFormat",
    "LeagueSettings",
    "LevelFactor",
    "LoadLog",
    "MinorLeagueBattingStats",
    "MissPopulationSummary",
    "MarginalValue",
    "Model",
    "ModelConfig",
    "OpportunityCost",
    "ModelRunRecord",
    "Ok",
    "OutcomeLabel",
    "PTSourceSummary",
    "PITCHING_COUNTING_STATS",
    "PITCHING_RATE_STATS",
    "PickGrade",
    "PickTrade",
    "PickTradeEvaluation",
    "PickValue",
    "PickValueCurve",
    "PitchingStats",
    "Player",
    "PlayerConfidence",
    "PooledCorrelationResult",
    "PlayerProfile",
    "ProjectedKeeper",
    "PlayerProjection",
    "PlayerRecommendation",
    "PlayerResidual",
    "PlayerStatDelta",
    "PlayerSummary",
    "PlayerTier",
    "PlayerUniverseProvider",
    "PlayerValuation",
    "PlayingTimeScenario",
    "OF_POSITIONS",
    "ROSTER_ONLY_POSITIONS",
    "Position",
    "PositionAppearance",
    "PositionRun",
    "consolidate_outfield",
    "position_from_raw",
    "Predictable",
    "PredictResult",
    "Preparable",
    "PrepareResult",
    "PositionUpgrade",
    "PositionScarcity",
    "PositionValueCurve",
    "ScarcityAdjustedPlayer",
    "Projection",
    "ProjectionComparison",
    "ReachPick",
    "Recommendation",
    "RecommendationWeights",
    "ResidualAnalysisReport",
    "ResidualAnalysisSummary",
    "ResidualPersistenceReport",
    "ResidualPersistenceSummary",
    "Result",
    "BudgetAllocation",
    "RoundTarget",
    "SnakeDraftPlan",
    "Roster",
    "RosterEntry",
    "RosterSlot",
    "RosterState",
    "RosterStint",
    "SimulationSummary",
    "SeasonCorrelationResult",
    "SgpDenominators",
    "SgpSeasonDenominator",
    "SeasonData",
    "SensitivityEntry",
    "SprintSpeed",
    "StatComparisonRecord",
    "StatDistribution",
    "StatMetrics",
    "StatResidualAnalysis",
    "StatResidualPersistence",
    "StatSpread",
    "StatTalentMetrics",
    "StatType",
    "Sweepable",
    "StabilityResult",
    "StatcastPitch",
    "StealOrReach",
    "StrategyComparison",
    "StratifiedComparisonResult",
    "SystemAccuracyResult",
    "SystemMetrics",
    "SystemSummary",
    "TeamCategoryProjection",
    "TeamKeeperProjection",
    "TailAccuracy",
    "ThresholdMetrics",
    "TalentQualitySummary",
    "TargetComparison",
    "TargetVector",
    "TargetCorrelation",
    "TargetExplorationResult",
    "TargetResult",
    "TargetStability",
    "TeamNeeds",
    "ThreatAssessment",
    "Team",
    "TierAssignment",
    "Trainable",
    "TrainResult",
    "TrainingBackend",
    "TradeEvaluation",
    "TradePlayerDetail",
    "TradeTarget",
    "Transaction",
    "TransactionPlayer",
    "TierSummaryEntry",
    "TierSummaryReport",
    "TrueTalentQualityReport",
    "Tunable",
    "TuneResult",
    "ValidationResult",
    "Valuation",
    "ValuationAccuracy",
    "ValuationComparisonResult",
    "ValuationEvalResult",
    "ValuationRegressionCheck",
    "check_valuation_regression",
    "ValueOverADP",
    "ValueOverADPReport",
    "VarianceClassification",
    "YahooDraftPick",
    "YahooLeague",
    "YahooPlayerMap",
    "TeamSeasonStats",
    "YahooTeam",
    "bucket_by_age",
    "bucket_by_experience",
    "bucket_by_handedness",
    "bucket_by_position",
    "build_consensus_lookup",
    "check_regression",
    "compare_to_batting_actuals",
    "compare_to_pitching_actuals",
    "current_season",
    "compute_age",
    "compute_calibration_bins",
    "compute_cohort_metrics",
    "compute_distinguishing_features",
    "compute_heteroscedasticity",
    "compute_mean_bias",
    "compute_miss_summary",
    "compute_predictive_validity",
    "compute_r_squared_with_buckets",
    "compute_residual_correlation_by_bucket",
    "compute_residual_yoy_correlation",
    "compute_rmse_ceiling",
    "compute_shrinkage",
    "compute_stat_metrics",
    "compute_tail_accuracy",
    "identify_chronic_performers",
    "missing_batting_comparisons",
    "missing_pitching_comparisons",
    "normalize_projection_pt",
    "resolve_playing_time",
    "rank_residuals",
    "split_direction",
    "split_residuals_by_quality",
    "summarize_comparison",
]
