CREATE TABLE IF NOT EXISTS minor_league_batting_stats (
    id       INTEGER PRIMARY KEY AUTOINCREMENT,
    player_id INTEGER NOT NULL REFERENCES player(id),
    season   INTEGER NOT NULL,
    level    TEXT NOT NULL,
    league   TEXT NOT NULL,
    team     TEXT NOT NULL,
    g        INTEGER NOT NULL,
    pa       INTEGER NOT NULL,
    ab       INTEGER NOT NULL,
    h        INTEGER NOT NULL,
    doubles  INTEGER NOT NULL,
    triples  INTEGER NOT NULL,
    hr       INTEGER NOT NULL,
    r        INTEGER NOT NULL,
    rbi      INTEGER NOT NULL,
    bb       INTEGER NOT NULL,
    so       INTEGER NOT NULL,
    sb       INTEGER NOT NULL,
    cs       INTEGER NOT NULL,
    avg      REAL NOT NULL,
    obp      REAL NOT NULL,
    slg      REAL NOT NULL,
    age      REAL NOT NULL,
    hbp      INTEGER,
    sf       INTEGER,
    sh       INTEGER,
    loaded_at TEXT,
    UNIQUE(player_id, season, level, team)
);
