from __future__ import annotations

from typing import TYPE_CHECKING, Protocol, runtime_checkable

if TYPE_CHECKING:
    import builtins

    from fantasy_baseball_manager.domain import (
        ADP,
        BattingStats,
        Experiment,
        FeatureCandidate,
        FeatureCheckpoint,
        ILStint,
        KeeperCost,
        LeagueEnvironment,
        LevelFactor,
        LoadLog,
        MinorLeagueBattingStats,
        ModelRunRecord,
        PitchingStats,
        Player,
        PositionAppearance,
        Projection,
        RosterStint,
        StatcastPitch,
        StatDistribution,
        Team,
        Valuation,
    )
    from fantasy_baseball_manager.repos.experiment_repo import ExperimentFilter


@runtime_checkable
class PlayerRepo(Protocol):
    def upsert(self, player: Player) -> int: ...
    def get_by_id(self, player_id: int) -> Player | None: ...
    def get_by_ids(self, player_ids: list[int]) -> list[Player]: ...
    def get_by_mlbam_id(self, mlbam_id: int) -> Player | None: ...
    def get_by_bbref_id(self, bbref_id: str) -> Player | None: ...
    def search_by_name(self, name: str) -> list[Player]: ...
    def get_by_last_name(self, last_name: str) -> list[Player]: ...
    def all(self) -> list[Player]: ...


@runtime_checkable
class TeamRepo(Protocol):
    def upsert(self, team: Team) -> int: ...
    def get_by_abbreviation(self, abbreviation: str) -> Team | None: ...
    def all(self) -> list[Team]: ...


@runtime_checkable
class BattingStatsRepo(Protocol):
    def upsert(self, stats: BattingStats) -> int: ...
    def get_by_player_season(self, player_id: int, season: int, source: str | None = None) -> list[BattingStats]: ...
    def get_by_season(self, season: int, source: str | None = None) -> list[BattingStats]: ...


@runtime_checkable
class PitchingStatsRepo(Protocol):
    def upsert(self, stats: PitchingStats) -> int: ...
    def get_by_player_season(self, player_id: int, season: int, source: str | None = None) -> list[PitchingStats]: ...
    def get_by_season(self, season: int, source: str | None = None) -> list[PitchingStats]: ...


@runtime_checkable
class ProjectionRepo(Protocol):
    def upsert(self, projection: Projection) -> int: ...
    def get_by_player_season(
        self, player_id: int, season: int, system: str | None = None, *, include_distributions: bool = False
    ) -> list[Projection]: ...
    def get_by_season(
        self, season: int, system: str | None = None, *, include_distributions: bool = False
    ) -> list[Projection]: ...
    def get_by_system_version(self, system: str, version: str) -> list[Projection]: ...
    def delete_by_system_version(self, system: str, version: str) -> int: ...
    def upsert_distributions(self, projection_id: int, distributions: list[StatDistribution]) -> None: ...
    def get_distributions(self, projection_id: int) -> list[StatDistribution]: ...


@runtime_checkable
class StatcastPitchRepo(Protocol):
    def upsert(self, pitch: StatcastPitch) -> int: ...
    def get_by_pitcher_date(self, pitcher_id: int, game_date: str) -> list[StatcastPitch]: ...
    def get_by_batter_date(self, batter_id: int, game_date: str) -> list[StatcastPitch]: ...
    def get_by_game(self, game_pk: int) -> list[StatcastPitch]: ...
    def count(self) -> int: ...


@runtime_checkable
class ModelRunRepo(Protocol):
    def upsert(self, record: ModelRunRecord) -> int: ...
    def get(self, system: str, version: str, operation: str = "train") -> ModelRunRecord | None: ...
    def list(self, system: str | None = None) -> builtins.list[ModelRunRecord]: ...
    def delete(self, system: str, version: str, operation: str = "train") -> None: ...


@runtime_checkable
class ILStintRepo(Protocol):
    def upsert(self, stint: ILStint) -> int: ...
    def get_by_player(self, player_id: int) -> list[ILStint]: ...
    def get_by_player_season(self, player_id: int, season: int) -> list[ILStint]: ...
    def get_by_season(self, season: int) -> list[ILStint]: ...


@runtime_checkable
class PositionAppearanceRepo(Protocol):
    def upsert(self, appearance: PositionAppearance) -> int: ...
    def get_by_player(self, player_id: int) -> list[PositionAppearance]: ...
    def get_by_player_season(self, player_id: int, season: int) -> list[PositionAppearance]: ...
    def get_by_season(self, season: int) -> list[PositionAppearance]: ...


@runtime_checkable
class RosterStintRepo(Protocol):
    def upsert(self, stint: RosterStint) -> int: ...
    def get_by_player(self, player_id: int) -> list[RosterStint]: ...
    def get_by_player_season(self, player_id: int, season: int) -> list[RosterStint]: ...
    def get_by_team_season(self, team_id: int, season: int) -> list[RosterStint]: ...
    def get_by_season(self, season: int) -> list[RosterStint]: ...


@runtime_checkable
class MinorLeagueBattingStatsRepo(Protocol):
    def upsert(self, stats: MinorLeagueBattingStats) -> int: ...
    def get_by_player(self, player_id: int) -> list[MinorLeagueBattingStats]: ...
    def get_by_player_season(self, player_id: int, season: int) -> list[MinorLeagueBattingStats]: ...
    def get_by_season_level(self, season: int, level: str) -> list[MinorLeagueBattingStats]: ...


@runtime_checkable
class LeagueEnvironmentRepo(Protocol):
    def upsert(self, env: LeagueEnvironment) -> int: ...
    def get_by_league_season_level(self, league: str, season: int, level: str) -> LeagueEnvironment | None: ...
    def get_by_season_level(self, season: int, level: str) -> list[LeagueEnvironment]: ...
    def get_by_season(self, season: int) -> list[LeagueEnvironment]: ...


@runtime_checkable
class LevelFactorRepo(Protocol):
    def upsert(self, factor: LevelFactor) -> int: ...
    def get_by_level_season(self, level: str, season: int) -> LevelFactor | None: ...
    def get_by_season(self, season: int) -> list[LevelFactor]: ...


@runtime_checkable
class LoadLogRepo(Protocol):
    def insert(self, log: LoadLog) -> int: ...
    def get_recent(self, limit: int = 20) -> list[LoadLog]: ...
    def get_by_target_table(self, target_table: str) -> list[LoadLog]: ...


@runtime_checkable
class ValuationRepo(Protocol):
    def upsert(self, valuation: Valuation) -> int: ...
    def get_by_player_season(self, player_id: int, season: int, system: str | None = None) -> list[Valuation]: ...
    def get_by_season(self, season: int, system: str | None = None) -> list[Valuation]: ...


@runtime_checkable
class ADPRepo(Protocol):
    def upsert(self, adp: ADP) -> int: ...
    def get_by_player_season(self, player_id: int, season: int) -> list[ADP]: ...
    def get_by_season(self, season: int, provider: str | None = None) -> list[ADP]: ...
    def get_snapshots(self, season: int, provider: str) -> list[str]: ...
    def get_by_snapshot(self, season: int, provider: str, as_of: str) -> list[ADP]: ...


@runtime_checkable
class ExperimentRepo(Protocol):
    def save(self, experiment: Experiment) -> int: ...
    def get(self, experiment_id: int) -> Experiment | None: ...
    def list(self, filter: ExperimentFilter | None = None) -> builtins.list[Experiment]: ...
    def find_by_target(self, target: str) -> builtins.list[Experiment]: ...
    def find_by_feature(self, column_name: str) -> builtins.list[Experiment]: ...
    def find_by_tag(self, tag: str) -> builtins.list[Experiment]: ...
    def find_by_model(self, model: str) -> builtins.list[Experiment]: ...
    def find_best(self, target: str, metric: str = "delta_pct") -> Experiment | None: ...
    def find_recent(self, n: int) -> builtins.list[Experiment]: ...
    def delete(self, experiment_id: int) -> None: ...


@runtime_checkable
class CheckpointRepo(Protocol):
    def save(self, checkpoint: FeatureCheckpoint, *, force: bool = False) -> None: ...
    def get(self, name: str, model: str) -> FeatureCheckpoint | None: ...
    def list(self, model: str | None = None) -> builtins.list[FeatureCheckpoint]: ...
    def delete(self, name: str, model: str) -> bool: ...


@runtime_checkable
class KeeperCostRepo(Protocol):
    def upsert_batch(self, costs: list[KeeperCost]) -> int: ...
    def find_by_season_league(self, season: int, league: str) -> list[KeeperCost]: ...
    def find_by_player(self, player_id: int) -> list[KeeperCost]: ...


@runtime_checkable
class FeatureCandidateRepo(Protocol):
    def save(self, candidate: FeatureCandidate) -> None: ...
    def get_by_name(self, name: str) -> FeatureCandidate | None: ...
    def list_all(self) -> builtins.list[FeatureCandidate]: ...
    def delete(self, name: str) -> bool: ...
