from __future__ import annotations

import builtins
from typing import Protocol, runtime_checkable

from fantasy_baseball_manager.domain.batting_stats import BattingStats
from fantasy_baseball_manager.domain.il_stint import ILStint
from fantasy_baseball_manager.domain.league_environment import LeagueEnvironment
from fantasy_baseball_manager.domain.level_factor import LevelFactor
from fantasy_baseball_manager.domain.load_log import LoadLog
from fantasy_baseball_manager.domain.minor_league_batting_stats import MinorLeagueBattingStats
from fantasy_baseball_manager.domain.position_appearance import PositionAppearance
from fantasy_baseball_manager.domain.roster_stint import RosterStint
from fantasy_baseball_manager.domain.model_run import ModelRunRecord
from fantasy_baseball_manager.domain.pitching_stats import PitchingStats
from fantasy_baseball_manager.domain.player import Player, Team
from fantasy_baseball_manager.domain.projection import Projection, StatDistribution
from fantasy_baseball_manager.domain.statcast_pitch import StatcastPitch
from fantasy_baseball_manager.domain.adp import ADP
from fantasy_baseball_manager.domain.valuation import Valuation


@runtime_checkable
class PlayerRepo(Protocol):
    def upsert(self, player: Player) -> int: ...
    def get_by_id(self, player_id: int) -> Player | None: ...
    def get_by_ids(self, player_ids: list[int]) -> list[Player]: ...
    def get_by_mlbam_id(self, mlbam_id: int) -> Player | None: ...
    def get_by_bbref_id(self, bbref_id: str) -> Player | None: ...
    def search_by_name(self, name: str) -> list[Player]: ...
    def get_by_last_name(self, last_name: str) -> list[Player]: ...
    def all(self) -> list[Player]: ...


@runtime_checkable
class TeamRepo(Protocol):
    def upsert(self, team: Team) -> int: ...
    def get_by_abbreviation(self, abbreviation: str) -> Team | None: ...
    def all(self) -> list[Team]: ...


@runtime_checkable
class BattingStatsRepo(Protocol):
    def upsert(self, stats: BattingStats) -> int: ...
    def get_by_player_season(self, player_id: int, season: int, source: str | None = None) -> list[BattingStats]: ...
    def get_by_season(self, season: int, source: str | None = None) -> list[BattingStats]: ...


@runtime_checkable
class PitchingStatsRepo(Protocol):
    def upsert(self, stats: PitchingStats) -> int: ...
    def get_by_player_season(self, player_id: int, season: int, source: str | None = None) -> list[PitchingStats]: ...
    def get_by_season(self, season: int, source: str | None = None) -> list[PitchingStats]: ...


@runtime_checkable
class ProjectionRepo(Protocol):
    def upsert(self, projection: Projection) -> int: ...
    def get_by_player_season(
        self, player_id: int, season: int, system: str | None = None, *, include_distributions: bool = False
    ) -> list[Projection]: ...
    def get_by_season(
        self, season: int, system: str | None = None, *, include_distributions: bool = False
    ) -> list[Projection]: ...
    def get_by_system_version(self, system: str, version: str) -> list[Projection]: ...
    def upsert_distributions(self, projection_id: int, distributions: list[StatDistribution]) -> None: ...
    def get_distributions(self, projection_id: int) -> list[StatDistribution]: ...


@runtime_checkable
class StatcastPitchRepo(Protocol):
    def upsert(self, pitch: StatcastPitch) -> int: ...
    def get_by_pitcher_date(self, pitcher_id: int, game_date: str) -> list[StatcastPitch]: ...
    def get_by_batter_date(self, batter_id: int, game_date: str) -> list[StatcastPitch]: ...
    def get_by_game(self, game_pk: int) -> list[StatcastPitch]: ...
    def count(self) -> int: ...


@runtime_checkable
class ModelRunRepo(Protocol):
    def upsert(self, record: ModelRunRecord) -> int: ...
    def get(self, system: str, version: str, operation: str = "train") -> ModelRunRecord | None: ...
    def list(self, system: str | None = None) -> builtins.list[ModelRunRecord]: ...
    def delete(self, system: str, version: str, operation: str = "train") -> None: ...


@runtime_checkable
class ILStintRepo(Protocol):
    def upsert(self, stint: ILStint) -> int: ...
    def get_by_player(self, player_id: int) -> list[ILStint]: ...
    def get_by_player_season(self, player_id: int, season: int) -> list[ILStint]: ...
    def get_by_season(self, season: int) -> list[ILStint]: ...


@runtime_checkable
class PositionAppearanceRepo(Protocol):
    def upsert(self, appearance: PositionAppearance) -> int: ...
    def get_by_player(self, player_id: int) -> list[PositionAppearance]: ...
    def get_by_player_season(self, player_id: int, season: int) -> list[PositionAppearance]: ...
    def get_by_season(self, season: int) -> list[PositionAppearance]: ...


@runtime_checkable
class RosterStintRepo(Protocol):
    def upsert(self, stint: RosterStint) -> int: ...
    def get_by_player(self, player_id: int) -> list[RosterStint]: ...
    def get_by_player_season(self, player_id: int, season: int) -> list[RosterStint]: ...
    def get_by_team_season(self, team_id: int, season: int) -> list[RosterStint]: ...
    def get_by_season(self, season: int) -> list[RosterStint]: ...


@runtime_checkable
class MinorLeagueBattingStatsRepo(Protocol):
    def upsert(self, stats: MinorLeagueBattingStats) -> int: ...
    def get_by_player(self, player_id: int) -> list[MinorLeagueBattingStats]: ...
    def get_by_player_season(self, player_id: int, season: int) -> list[MinorLeagueBattingStats]: ...
    def get_by_season_level(self, season: int, level: str) -> list[MinorLeagueBattingStats]: ...


@runtime_checkable
class LeagueEnvironmentRepo(Protocol):
    def upsert(self, env: LeagueEnvironment) -> int: ...
    def get_by_league_season_level(self, league: str, season: int, level: str) -> LeagueEnvironment | None: ...
    def get_by_season_level(self, season: int, level: str) -> list[LeagueEnvironment]: ...
    def get_by_season(self, season: int) -> list[LeagueEnvironment]: ...


@runtime_checkable
class LevelFactorRepo(Protocol):
    def upsert(self, factor: LevelFactor) -> int: ...
    def get_by_level_season(self, level: str, season: int) -> LevelFactor | None: ...
    def get_by_season(self, season: int) -> list[LevelFactor]: ...


@runtime_checkable
class LoadLogRepo(Protocol):
    def insert(self, log: LoadLog) -> int: ...
    def get_recent(self, limit: int = 20) -> list[LoadLog]: ...
    def get_by_target_table(self, target_table: str) -> list[LoadLog]: ...


@runtime_checkable
class ValuationRepo(Protocol):
    def upsert(self, valuation: Valuation) -> int: ...
    def get_by_player_season(self, player_id: int, season: int, system: str | None = None) -> list[Valuation]: ...
    def get_by_season(self, season: int, system: str | None = None) -> list[Valuation]: ...


@runtime_checkable
class ADPRepo(Protocol):
    def upsert(self, adp: ADP) -> int: ...
    def get_by_player_season(self, player_id: int, season: int) -> list[ADP]: ...
    def get_by_season(self, season: int, provider: str | None = None) -> list[ADP]: ...
    def get_snapshots(self, season: int, provider: str) -> list[str]: ...
    def get_by_snapshot(self, season: int, provider: str, as_of: str) -> list[ADP]: ...
