from __future__ import annotations

import builtins
from typing import Protocol, runtime_checkable

from fantasy_baseball_manager.domain.batting_stats import BattingStats
from fantasy_baseball_manager.domain.il_stint import ILStint
from fantasy_baseball_manager.domain.load_log import LoadLog
from fantasy_baseball_manager.domain.model_run import ModelRunRecord
from fantasy_baseball_manager.domain.pitching_stats import PitchingStats
from fantasy_baseball_manager.domain.player import Player, Team
from fantasy_baseball_manager.domain.projection import Projection, StatDistribution
from fantasy_baseball_manager.domain.statcast_pitch import StatcastPitch


@runtime_checkable
class PlayerRepo(Protocol):
    def upsert(self, player: Player) -> int: ...
    def get_by_id(self, player_id: int) -> Player | None: ...
    def get_by_mlbam_id(self, mlbam_id: int) -> Player | None: ...
    def get_by_bbref_id(self, bbref_id: str) -> Player | None: ...
    def search_by_name(self, name: str) -> list[Player]: ...
    def get_by_last_name(self, last_name: str) -> list[Player]: ...
    def all(self) -> list[Player]: ...


@runtime_checkable
class TeamRepo(Protocol):
    def upsert(self, team: Team) -> int: ...
    def get_by_abbreviation(self, abbreviation: str) -> Team | None: ...
    def all(self) -> list[Team]: ...


@runtime_checkable
class BattingStatsRepo(Protocol):
    def upsert(self, stats: BattingStats) -> int: ...
    def get_by_player_season(self, player_id: int, season: int, source: str | None = None) -> list[BattingStats]: ...
    def get_by_season(self, season: int, source: str | None = None) -> list[BattingStats]: ...


@runtime_checkable
class PitchingStatsRepo(Protocol):
    def upsert(self, stats: PitchingStats) -> int: ...
    def get_by_player_season(self, player_id: int, season: int, source: str | None = None) -> list[PitchingStats]: ...
    def get_by_season(self, season: int, source: str | None = None) -> list[PitchingStats]: ...


@runtime_checkable
class ProjectionRepo(Protocol):
    def upsert(self, projection: Projection) -> int: ...
    def get_by_player_season(
        self, player_id: int, season: int, system: str | None = None, *, include_distributions: bool = False
    ) -> list[Projection]: ...
    def get_by_season(
        self, season: int, system: str | None = None, *, include_distributions: bool = False
    ) -> list[Projection]: ...
    def get_by_system_version(self, system: str, version: str) -> list[Projection]: ...
    def upsert_distributions(self, projection_id: int, distributions: list[StatDistribution]) -> None: ...
    def get_distributions(self, projection_id: int) -> list[StatDistribution]: ...


@runtime_checkable
class StatcastPitchRepo(Protocol):
    def upsert(self, pitch: StatcastPitch) -> int: ...
    def get_by_pitcher_date(self, pitcher_id: int, game_date: str) -> list[StatcastPitch]: ...
    def get_by_batter_date(self, batter_id: int, game_date: str) -> list[StatcastPitch]: ...
    def get_by_game(self, game_pk: int) -> list[StatcastPitch]: ...
    def count(self) -> int: ...


@runtime_checkable
class ModelRunRepo(Protocol):
    def upsert(self, record: ModelRunRecord) -> int: ...
    def get(self, system: str, version: str, operation: str = "train") -> ModelRunRecord | None: ...
    def list(self, system: str | None = None) -> builtins.list[ModelRunRecord]: ...
    def delete(self, system: str, version: str, operation: str = "train") -> None: ...


@runtime_checkable
class ILStintRepo(Protocol):
    def upsert(self, stint: ILStint) -> int: ...
    def get_by_player(self, player_id: int) -> list[ILStint]: ...
    def get_by_player_season(self, player_id: int, season: int) -> list[ILStint]: ...
    def get_by_season(self, season: int) -> list[ILStint]: ...


@runtime_checkable
class LoadLogRepo(Protocol):
    def insert(self, log: LoadLog) -> int: ...
    def get_recent(self, limit: int = 20) -> list[LoadLog]: ...
    def get_by_target_table(self, target_table: str) -> list[LoadLog]: ...
